spring:
  application:
    name: example-server
server:
  port: 8002

rpc:
  server:
    netty:
      host: 127.0.0.1
      port: 8888
    socket:
      port: 7777 # Server端口
      host: 127.0.0.1 # Server地址
    registry:
      zookeeper:
        address: 192.168.170.129:2181



