spring:
  application:
    name: example-server
server:
  port: 8003

rpc:
  server:
    netty:
      port: 8887 # netty端口
      host: 127.0.0.1 # netty地址
    socket:
      port: 7776 # socket端口
      host: 127.0.0.1 # socket地址
    registry:
      zookeeper:
        address: 192.168.170.129:2181