spring:
  application:
    name: example-client
server:
  port: 8001



rpc:
  server:
    netty:
      port: 8881 # netty端口
      host: 127.0.0.1 # netty地址
    socket:
      port: 7773 # socket端口
      host: 127.0.0.1 # socket地址
    registry:
      zookeeper:
        address: 192.168.170.129:2181
  transport:
    type: netty